export const PRODUCTS_REPOSITORY = 'PRODUCTS_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
export const CART_REPOSITORY = 'CART_REPOSITORY';
export const PRODUCTS_IN_CART_REPOSITORY = 'PRODUCTS_IN_CART_REPOSITORY';
